name: Build and Publish Package

on:
  push:
    branches:
      - master
    paths:
      - 'src/main/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: false
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Create settings.xml from the GitHub secrets for PremiumPoints and ColdDev
      - name: Create settings.xml
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/settings.xml
          <settings>
            <servers>
              <server>
                <id>com.github.padrewin</id>
                <username>padrewin</username>
                <password>${{ secrets.PREMIUMPOINTS_PACKAGE }}</password>
              </server>
              <server>
                <id>com.github.coldplugin</id>
                <username>padrewin</username>
                <password>${{ secrets.COLDDEV_PACKAGE }}</password>
              </server>
            </servers>
          </settings>
          EOF

      # Build the project using Maven
      - name: Build with Maven
        run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: "contains(github.event.commits[0].message, '[build]')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Re-create settings.xml from the GitHub secrets for PremiumPoints and ColdDev
      - name: Create settings.xml
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/settings.xml
          <settings>
            <servers>
              <server>
                <id>com.github.padrewin</id>
                <username>padrewin</username>
                <password>${{ secrets.PREMIUMPOINTS_PACKAGE }}</password>
              </server>
              <server>
                <id>com.github.coldplugin</id>
                <username>padrewin</username>
                <password>${{ secrets.COLDDEV_PACKAGE }}</password>
              </server>
            </servers>
          </settings>
          EOF

      # Deploy the package to GitHub Packages using Maven
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml